import sys
from pathlib import Path

import mkdocs_gen_files

from mkdocs_sqlalchemy_plugin.config import (
    DisplayConfig,
    FilterConfig,
    PluginConfig,
    TableStyleConfig,
)
from mkdocs_sqlalchemy_plugin.markdown import (
    SqlAlchemyPluginContext,
    generate_table,
    generate_tables,
)


def get_fixture_base(fixture_name: str):
    fixture_path = Path.cwd() / f"tests/fixtures/{fixture_name}/src"
    if str(fixture_path) not in sys.path:
        sys.path.append(str(fixture_path))

    module_name = f"{fixture_name}.models"
    if module_name in sys.modules:
        del sys.modules[module_name]

    import importlib

    module = importlib.import_module(module_name)
    return module.Base


def update_file(file_path: Path, content: str):
    current_content = file_path.read_text()
    if "\{\% autogenerated_example \%\}" in current_content:
        current_content = current_content.split("## Result")[0]

    new_content = current_content.replace(
        "{% autogenerated_example %}",
        "---\n" + "## Result\n\n" + content + "\n",
    )
    # Remove 'docs/' prefix if present
    rel_path = file_path
    if str(file_path).startswith("docs/"):
        rel_path = Path(str(file_path)[5:])
    with mkdocs_gen_files.open(rel_path, "w") as f:
        print(new_content, file=f)
    print(f"Updated {rel_path}")


def run_basic_setup():
    Base = get_fixture_base("basic_setup")
    config = PluginConfig(
        base_class="basic_setup.models.Base",
        table_style=TableStyleConfig(),
        filter=FilterConfig(),
        display=DisplayConfig(),
    )
    context = SqlAlchemyPluginContext(base_class=Base, plugin_config=config)
    markdown = generate_tables(context)
    update_file(Path("docs/howto/basic_setup.md"), markdown)


def run_by_schema():
    Base = get_fixture_base("by_schema")
    config = PluginConfig(
        base_class="by_schema.models.Base",
        table_style=TableStyleConfig(),
        filter=FilterConfig(),
        display=DisplayConfig(group_by_schema=True),
    )
    context = SqlAlchemyPluginContext(base_class=Base, plugin_config=config)
    from mkdocs_sqlalchemy_plugin.markdown import generate_tables_by_schema

    markdown = generate_tables_by_schema(context)
    update_file(Path("docs/howto/by_schema.md"), markdown)


def run_filter_fields():
    Base = get_fixture_base("filter_fields")
    config = PluginConfig(
        base_class="filter_fields.models.Base",
        table_style=TableStyleConfig(fields=["column", "type", "nullable"]),
        filter=FilterConfig(),
        display=DisplayConfig(),
    )
    context = SqlAlchemyPluginContext(base_class=Base, plugin_config=config)
    markdown = generate_tables(context)
    update_file(Path("docs/howto/filter_fields.md"), markdown)


def run_show_sql():
    Base = get_fixture_base("show_sql")
    config = PluginConfig(
        base_class="show_sql.models.Base",
        table_style=TableStyleConfig(),
        filter=FilterConfig(),
        display=DisplayConfig(show_sql=True),
    )
    context = SqlAlchemyPluginContext(base_class=Base, plugin_config=config)
    markdown = generate_tables(context)
    update_file(Path("docs/howto/show_sql.md"), markdown)


def run_single_tables():
    Base = get_fixture_base("single_tables")
    config = PluginConfig(
        base_class="single_tables.models.Base",
        table_style=TableStyleConfig(),
        filter=FilterConfig(),
        display=DisplayConfig(),
    )
    context = SqlAlchemyPluginContext(base_class=Base, plugin_config=config)

    markdown_users = generate_table(context, "users")
    markdown_posts = generate_table(context, "posts")

    content = (
        f"### Users Table\n\n{markdown_users}\n\n### Posts Table\n\n{markdown_posts}"
    )
    update_file(Path("docs/howto/single_tables.md"), content)


def run_table_style():
    Base = get_fixture_base("table_style")
    config = PluginConfig(
        base_class="table_style.models.Base",
        table_style=TableStyleConfig(
            tick="y", cross="n", heading_level=2, text_align="left"
        ),
        filter=FilterConfig(),
        display=DisplayConfig(),
    )
    context = SqlAlchemyPluginContext(base_class=Base, plugin_config=config)
    markdown = generate_tables(context)
    update_file(Path("docs/howto/table_style.md"), markdown)


def main():
    run_basic_setup()
    run_by_schema()
    run_filter_fields()
    run_show_sql()
    run_single_tables()
    run_table_style()


main()
